# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_FINGERPRINT_EGIS520) +=et520.o
obj-$(CONFIG_FINGERPRINT_EGIS520) +=ets_navi_input.o

